Send Done-melding for uleste utbetalinger
navikt/spinnsyn-backend pull request #308
Opened 2022-01-10 09:44 UTC by nilsjorgen

Gjelder kun uleste utbetalinger som er varslet av spinnsyn-backend.

2022-01-10 10:39 UTC, heyvard requested changes

2022-01-10 10:39 UTC, heyvard commented on src/main/resources/application.yaml
> +      maximum-pool-size: 10
hmm, er det nok connections gitt antall pods?

2022-01-10 10:47 UTC, heyvard requested changes

2022-01-10 10:47 UTC, heyvard commented on src/main/resources/db/migration/V32__fyll_done_tabell.sql
> +FROM utbetaling
hva med vedtak tabellen?

2022-01-10 10:47 UTC, heyvard commented on src/main/resources/db/migration/V32__fyll_done_tabell.sql
> +SELECT id, fnr
Skal ikke varsletMed brukes istedenfor id?

2022-01-10 11:32 UTC, nilsjorgen commented on src/main/resources/db/migration/V32__fyll_done_tabell.sql
> +SELECT id, fnr
Jo, endrer til varsletMed.

2022-01-10 11:33 UTC, nilsjorgen commented on src/main/resources/db/migration/V32__fyll_done_tabell.sql
> +FROM utbetaling
Den trodde vi var ferdig lest, men det viste seg at `count(lest)` selvsagt blir 0 siden count ikke teller NULL-verdier.

2022-01-10 11:33 UTC, nilsjorgen commented on src/main/resources/application.yaml
> +      maximum-pool-size: 10
Sjekker opp max antall connections i GCP og justerer.

2022-01-11 08:22 UTC, nilsjorgen commented on src/main/resources/application.yaml
> +      maximum-pool-size: 10
SELECT * FROM pg_settings WHERE name = 'max_connections';
-- 25

spinnsyn-db makser på 9 jevnlig, cloudsql_db bruker 5, så maks siste uke har vært 14 connections, så tåler nok fint at vi setter maks connections til 5.

2022-01-11 10:43 UTC, heyvard approved these changes

2022-01-12 19:47 UTC, merged